apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    url: http://loki:3100
    jsonData:
      # This is the "Magic Link" that connects Logs to Traces
      derivedFields:
        - datasourceUid: 'jaeger'
          matcherRegex: '"trace_id":\s*"(\w+)"'
          name: TraceID
          url: '$${__value.raw}'
  
