"""init

Revision ID: 02ee28237972
Revises: 
Create Date: 2026-04-02 14:02:20.393609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02ee28237972'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('champion',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('champion_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_champion_champion_name'), 'champion', ['champion_name'], unique=False)
    op.create_index(op.f('ix_champion_id'), 'champion', ['id'], unique=False)
    op.create_table('match',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=True),
    sa.Column('ended', sa.Integer(), nullable=True),
    sa.Column('gametype', sa.String(), nullable=True),
    sa.Column('patch', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_id'), 'match', ['id'], unique=False)
    op.create_table('matches_analyzed',
    sa.Column('patch', sa.String(), nullable=False),
    sa.Column('gametype', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('patch', 'gametype')
    )
    op.create_index(op.f('ix_matches_analyzed_gametype'), 'matches_analyzed', ['gametype'], unique=False)
    op.create_index(op.f('ix_matches_analyzed_patch'), 'matches_analyzed', ['patch'], unique=False)
    op.create_table('summoner',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('summoner_name', sa.String(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_won', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summoner_id'), 'summoner', ['id'], unique=False)
    op.create_table('champion_stats',
    sa.Column('champion_id', sa.String(), nullable=False),
    sa.Column('patch', sa.String(), nullable=False),
    sa.Column('gametype', sa.String(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_won', sa.Integer(), nullable=True),
    sa.Column('games_banned', sa.Integer(), nullable=True),
    sa.Column('kill', sa.Integer(), nullable=True),
    sa.Column('assist', sa.Integer(), nullable=True),
    sa.Column('death', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['champion_id'], ['champion.id'], ),
    sa.PrimaryKeyConstraint('champion_id', 'patch', 'gametype')
    )
    op.create_index(op.f('ix_champion_stats_champion_id'), 'champion_stats', ['champion_id'], unique=False)
    op.create_index(op.f('ix_champion_stats_gametype'), 'champion_stats', ['gametype'], unique=False)
    op.create_index(op.f('ix_champion_stats_patch'), 'champion_stats', ['patch'], unique=False)
    op.create_table('match_participant',
    sa.Column('summoner_id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('kill', sa.Integer(), nullable=True),
    sa.Column('assist', sa.Integer(), nullable=True),
    sa.Column('death', sa.Integer(), nullable=True),
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.Column('won', sa.Boolean(), nullable=True),
    sa.Column('champion', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['champion'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['summoner_id'], ['summoner.id'], ),
    sa.PrimaryKeyConstraint('summoner_id', 'match_id')
    )
    op.create_index(op.f('ix_match_participant_match_id'), 'match_participant', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_participant_summoner_id'), 'match_participant', ['summoner_id'], unique=False)
    op.create_table('summoner_champion',
    sa.Column('summoner_id', sa.String(), nullable=False),
    sa.Column('champion_id', sa.String(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_won', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['champion_id'], ['champion.id'], ),
    sa.ForeignKeyConstraint(['summoner_id'], ['summoner.id'], ),
    sa.PrimaryKeyConstraint('summoner_id', 'champion_id')
    )
    op.create_index(op.f('ix_summoner_champion_champion_id'), 'summoner_champion', ['champion_id'], unique=False)
    op.create_index(op.f('ix_summoner_champion_summoner_id'), 'summoner_champion', ['summoner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summoner_champion_summoner_id'), table_name='summoner_champion')
    op.drop_index(op.f('ix_summoner_champion_champion_id'), table_name='summoner_champion')
    op.drop_table('summoner_champion')
    op.drop_index(op.f('ix_match_participant_summoner_id'), table_name='match_participant')
    op.drop_index(op.f('ix_match_participant_match_id'), table_name='match_participant')
    op.drop_table('match_participant')
    op.drop_index(op.f('ix_champion_stats_patch'), table_name='champion_stats')
    op.drop_index(op.f('ix_champion_stats_gametype'), table_name='champion_stats')
    op.drop_index(op.f('ix_champion_stats_champion_id'), table_name='champion_stats')
    op.drop_table('champion_stats')
    op.drop_index(op.f('ix_summoner_id'), table_name='summoner')
    op.drop_table('summoner')
    op.drop_index(op.f('ix_matches_analyzed_patch'), table_name='matches_analyzed')
    op.drop_index(op.f('ix_matches_analyzed_gametype'), table_name='matches_analyzed')
    op.drop_table('matches_analyzed')
    op.drop_index(op.f('ix_match_id'), table_name='match')
    op.drop_table('match')
    op.drop_index(op.f('ix_champion_id'), table_name='champion')
    op.drop_index(op.f('ix_champion_champion_name'), table_name='champion')
    op.drop_table('champion')
    # ### end Alembic commands ###
