"""trigers

Revision ID: 3f0e1eb169c4
Revises: 02ee28237972
Create Date: 2026-04-02 14:02:50.224365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f0e1eb169c4'
down_revision: Union[str, Sequence[str], None] = '02ee28237972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
    CREATE OR REPLACE FUNCTION increment_analyzed_count()
    RETURNS TRIGGER AS $$
    BEGIN
        INSERT INTO matches_analyzed (gametype, patch, count)
        VALUES (NEW.gametype, NEW.patch, 1) ON CONFLICT (gametype, patch)
        DO UPDATE
        SET count = matches_analyzed.count + 1;

        RETURN NEW;
    END;
    $$  LANGUAGE plpgsql;

    CREATE TRIGGER participant_alalyze_trigger
        AFTER INSERT
        ON match
        FOR EACH ROW
        EXECUTE FUNCTION increment_analyzed_count();





    CREATE OR REPLACE FUNCTION increment_champion_stats()
    RETURNS TRIGGER AS $$
    BEGIN
        
        INSERT INTO champion_stats (champion_id, patch, gametype,games_played,games_won,games_banned,kill,assist,death)
        SELECT 
            new.champion,
            m.patch, 
            m.gametype, 
            1, 
            CASE WHEN NEW.won THEN 1 ELSE 0 END,
            0,
            new.kill,
            new.assist,
            new.death
        FROM match m
        WHERE m.id = NEW.match_id
        ON CONFLICT (champion_id,gametype, patch)
        DO UPDATE
        SET 
            games_played = champion_stats.games_played + 1,
            games_won = COALESCE(champion_stats.games_won, 0) + 
                CASE WHEN NEW.won THEN 1 ELSE 0 END,
            kill = champion_stats.kill + new.kill,
            assist = champion_stats.assist + new.assist,
            death = champion_stats.death + new.death;

        RETURN NEW;
    END;
    $$  LANGUAGE plpgsql;

    CREATE TRIGGER participant_champion_trigger
        AFTER INSERT
        ON match_participant
        FOR EACH ROW
        EXECUTE FUNCTION increment_champion_stats();






    CREATE OR REPLACE FUNCTION increment_summoner_games()
    RETURNS TRIGGER AS $$
    BEGIN
        
        UPDATE summoner
        SET 
        games_played = COALESCE(games_played, 0) + 1,
        games_won = COALESCE(games_won, 0) + 
            CASE WHEN NEW.won THEN 1 ELSE 0 END
        WHERE id = NEW.summoner_id;

        RETURN NEW;
    END;
    $$  LANGUAGE plpgsql;

    CREATE TRIGGER Summoner_trigger
        AFTER INSERT
        ON match_participant
        FOR EACH ROW
        EXECUTE FUNCTION increment_summoner_games();


    
    CREATE OR REPLACE FUNCTION increment_summoner_champion()
    RETURNS TRIGGER AS $$
    BEGIN
        
        INSERT INTO summoner_champion (summoner_id,champion_id, games_played,games_won)
        SELECT 
            new.summoner_id,
            new.champion,
            1, 
            CASE WHEN NEW.won THEN 1 ELSE 0 END
        ON CONFLICT (summoner_id,champion_id)
        DO UPDATE
        SET 
            games_played = summoner_champion.games_played + 1,
            games_won = COALESCE(summoner_champion.games_won, 0) + 
                CASE WHEN NEW.won THEN 1 ELSE 0 END;
        
        RETURN NEW;
    END;
    $$  LANGUAGE plpgsql;

    CREATE TRIGGER Summoner_champion_trigger
        AFTER INSERT
        ON match_participant
        FOR EACH ROW
        EXECUTE FUNCTION increment_summoner_champion();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

    op.execute("""
    DROP FUNCTION IF EXISTS increment_analyzed_count();
    DROP FUNCTION IF EXISTS increment_champion_stats();
    DROP FUNCTION IF EXISTS increment_summoner_champion();
    DROP FUNCTION IF EXISTS increment_summoner_games();
    
    
    DROP TRIGGER IF EXISTS participant_alalyze_trigger ON match;
    DROP TRIGGER IF EXISTS participant_champion_trigger ON match_participant;
    DROP TRIGGER IF EXISTS Summoner_trigger ON match_participant;
    DROP TRIGGER IF EXISTS Summoner_champion_trigger ON match_participant;
    """)
