"""banrate_trigger

Revision ID: 50ee3ad46c2e
Revises: 0380f923d692
Create Date: 2026-04-24 19:04:49.856082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ee3ad46c2e'
down_revision: Union[str, Sequence[str], None] = '0380f923d692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

    op.execute("""
    CREATE OR REPLACE FUNCTION increment_champion_ban()
    RETURNS TRIGGER AS $$
    BEGIN
        INSERT INTO champion_stats (champion_id, patch, queue_id,games_played,games_won,games_banned,kill,assist,death)
        SELECT 
            ch.id,
            m.patch, 
            m.queue_id, 
            0, 
            0,
            1,
            0,
            0,
            0
        FROM champion ch
        JOIN "match" m ON m.id = NEW.match_id
        WHERE ch.key = NEW.champion_key
        ON CONFLICT (champion_id,queue_id, patch)
        DO UPDATE
        SET 
            games_banned = champion_stats.games_banned + 1;
        RETURN NEW;
    END;
    $$  LANGUAGE plpgsql;

    DROP TRIGGER IF EXISTS ban_trigger ON ban;
    CREATE TRIGGER ban_trigger
        AFTER INSERT
        ON ban
        FOR EACH ROW
        WHEN (NEW.champion_key > -1) EXECUTE FUNCTION increment_champion_ban();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
