"""init

Revision ID: 89d6f7279c4d
Revises: 
Create Date: 2026-03-26 14:24:14.796267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89d6f7279c4d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Champion',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('champion_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Champion_champion_name'), 'Champion', ['champion_name'], unique=False)
    op.create_index(op.f('ix_Champion_id'), 'Champion', ['id'], unique=False)
    op.create_table('Champion_Stats',
    sa.Column('champion_name', sa.String(), nullable=False),
    sa.Column('patch', sa.String(), nullable=False),
    sa.Column('gametype', sa.String(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_won', sa.Integer(), nullable=True),
    sa.Column('games_banned', sa.Integer(), nullable=True),
    sa.Column('kill', sa.Integer(), nullable=True),
    sa.Column('assist', sa.Integer(), nullable=True),
    sa.Column('death', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('champion_name', 'patch', 'gametype')
    )
    op.create_index(op.f('ix_Champion_Stats_champion_name'), 'Champion_Stats', ['champion_name'], unique=False)
    op.create_index(op.f('ix_Champion_Stats_gametype'), 'Champion_Stats', ['gametype'], unique=False)
    op.create_index(op.f('ix_Champion_Stats_patch'), 'Champion_Stats', ['patch'], unique=False)
    op.create_table('Match',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=True),
    sa.Column('ended', sa.Integer(), nullable=True),
    sa.Column('gametype', sa.String(), nullable=True),
    sa.Column('patch', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Match_id'), 'Match', ['id'], unique=False)
    op.create_table('Match_Participant',
    sa.Column('summoner_id', sa.String(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('kill', sa.Integer(), nullable=True),
    sa.Column('assist', sa.Integer(), nullable=True),
    sa.Column('death', sa.Integer(), nullable=True),
    sa.Column('gold', sa.Integer(), nullable=True),
    sa.Column('team', sa.Integer(), nullable=True),
    sa.Column('won', sa.Boolean(), nullable=True),
    sa.Column('champion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('summoner_id', 'match_id')
    )
    op.create_index(op.f('ix_Match_Participant_match_id'), 'Match_Participant', ['match_id'], unique=False)
    op.create_index(op.f('ix_Match_Participant_summoner_id'), 'Match_Participant', ['summoner_id'], unique=False)
    op.create_table('Summoner',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('summoner_name', sa.String(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_won', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Summoner_id'), 'Summoner', ['id'], unique=False)
    op.create_table('Summoner_Champion',
    sa.Column('summoner_id', sa.String(), nullable=False),
    sa.Column('champion_name', sa.String(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('games_won', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('summoner_id', 'champion_name')
    )
    op.create_index(op.f('ix_Summoner_Champion_champion_name'), 'Summoner_Champion', ['champion_name'], unique=False)
    op.create_index(op.f('ix_Summoner_Champion_summoner_id'), 'Summoner_Champion', ['summoner_id'], unique=False)
    op.create_table('matches_Analyzed',
    sa.Column('patch', sa.String(), nullable=False),
    sa.Column('gametype', sa.String(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('patch', 'gametype')
    )
    op.create_index(op.f('ix_matches_Analyzed_gametype'), 'matches_Analyzed', ['gametype'], unique=False)
    op.create_index(op.f('ix_matches_Analyzed_patch'), 'matches_Analyzed', ['patch'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matches_Analyzed_patch'), table_name='matches_Analyzed')
    op.drop_index(op.f('ix_matches_Analyzed_gametype'), table_name='matches_Analyzed')
    op.drop_table('matches_Analyzed')
    op.drop_index(op.f('ix_Summoner_Champion_summoner_id'), table_name='Summoner_Champion')
    op.drop_index(op.f('ix_Summoner_Champion_champion_name'), table_name='Summoner_Champion')
    op.drop_table('Summoner_Champion')
    op.drop_index(op.f('ix_Summoner_id'), table_name='Summoner')
    op.drop_table('Summoner')
    op.drop_index(op.f('ix_Match_Participant_summoner_id'), table_name='Match_Participant')
    op.drop_index(op.f('ix_Match_Participant_match_id'), table_name='Match_Participant')
    op.drop_table('Match_Participant')
    op.drop_index(op.f('ix_Match_id'), table_name='Match')
    op.drop_table('Match')
    op.drop_index(op.f('ix_Champion_Stats_patch'), table_name='Champion_Stats')
    op.drop_index(op.f('ix_Champion_Stats_gametype'), table_name='Champion_Stats')
    op.drop_index(op.f('ix_Champion_Stats_champion_name'), table_name='Champion_Stats')
    op.drop_table('Champion_Stats')
    op.drop_index(op.f('ix_Champion_id'), table_name='Champion')
    op.drop_index(op.f('ix_Champion_champion_name'), table_name='Champion')
    op.drop_table('Champion')
    # ### end Alembic commands ###
