"""inserting champions

Revision ID: b53b79809d27
Revises: e2cd94cc629b
Create Date: 2026-04-21 19:26:20.262808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = 'b53b79809d27'
down_revision: Union[str, Sequence[str], None] = 'e2cd94cc629b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    query = text("""
                 INSERT INTO champion (id, champion_name)
                 VALUES (:id, :name) ON CONFLICT (id) DO NOTHING
                 """)

    conn.execute(query, {"id": "Aatrox", "name": "Aatrox"})
    conn.execute(query, {"id": "Ahri", "name": "Ahri"})
    conn.execute(query, {"id": "Akali", "name": "Akali"})
    conn.execute(query, {"id": "Akshan", "name": "Akshan"})
    conn.execute(query, {"id": "Alistar", "name": "Alistar"})
    conn.execute(query, {"id": "Amumu", "name": "Amumu"})
    conn.execute(query, {"id": "Anivia", "name": "Anivia"})
    conn.execute(query, {"id": "Annie", "name": "Annie"})
    conn.execute(query, {"id": "Aphelios", "name": "Aphelios"})
    conn.execute(query, {"id": "Ashe", "name": "Ashe"})
    conn.execute(query, {"id": "AurelionSol", "name": "Aurelion Sol"})
    conn.execute(query, {"id": "Azir", "name": "Azir"})
    conn.execute(query, {"id": "Bard", "name": "Bard"})
    conn.execute(query, {"id": "Belveth", "name": "Bel'Veth"})
    conn.execute(query, {"id": "Blitzcrank", "name": "Blitzcrank"})
    conn.execute(query, {"id": "Brand", "name": "Brand"})
    conn.execute(query, {"id": "Braum", "name": "Braum"})
    conn.execute(query, {"id": "Caitlyn", "name": "Caitlyn"})
    conn.execute(query, {"id": "Camille", "name": "Camille"})
    conn.execute(query, {"id": "Cassiopeia", "name": "Cassiopeia"})
    conn.execute(query, {"id": "Chogath", "name": "Cho'Gath"})
    conn.execute(query, {"id": "Corki", "name": "Corki"})
    conn.execute(query, {"id": "Darius", "name": "Darius"})
    conn.execute(query, {"id": "Diana", "name": "Diana"})
    conn.execute(query, {"id": "Draven", "name": "Draven"})
    conn.execute(query, {"id": "DrMundo", "name": "Dr. Mundo"})
    conn.execute(query, {"id": "Ekko", "name": "Ekko"})
    conn.execute(query, {"id": "Elise", "name": "Elise"})
    conn.execute(query, {"id": "Evelynn", "name": "Evelynn"})
    conn.execute(query, {"id": "Ezreal", "name": "Ezreal"})
    conn.execute(query, {"id": "Fiddlesticks", "name": "Fiddlesticks"})
    conn.execute(query, {"id": "Fiora", "name": "Fiora"})
    conn.execute(query, {"id": "Fizz", "name": "Fizz"})
    conn.execute(query, {"id": "Galio", "name": "Galio"})
    conn.execute(query, {"id": "Gangplank", "name": "Gangplank"})
    conn.execute(query, {"id": "Garen", "name": "Garen"})
    conn.execute(query, {"id": "Gnar", "name": "Gnar"})
    conn.execute(query, {"id": "Gragas", "name": "Gragas"})
    conn.execute(query, {"id": "Graves", "name": "Graves"})
    conn.execute(query, {"id": "Gwen", "name": "Gwen"})
    conn.execute(query, {"id": "Hecarim", "name": "Hecarim"})
    conn.execute(query, {"id": "Heimerdinger", "name": "Heimerdinger"})
    conn.execute(query, {"id": "Illaoi", "name": "Illaoi"})
    conn.execute(query, {"id": "Irelia", "name": "Irelia"})
    conn.execute(query, {"id": "Ivern", "name": "Ivern"})
    conn.execute(query, {"id": "Janna", "name": "Janna"})
    conn.execute(query, {"id": "JarvanIV", "name": "Jarvan IV"})
    conn.execute(query, {"id": "Jax", "name": "Jax"})
    conn.execute(query, {"id": "Jayce", "name": "Jayce"})
    conn.execute(query, {"id": "Jhin", "name": "Jhin"})
    conn.execute(query, {"id": "Jinx", "name": "Jinx"})
    conn.execute(query, {"id": "Kaisa", "name": "Kai'Sa"})
    conn.execute(query, {"id": "Kalista", "name": "Kalista"})
    conn.execute(query, {"id": "Karma", "name": "Karma"})
    conn.execute(query, {"id": "Karthus", "name": "Karthus"})
    conn.execute(query, {"id": "Kassadin", "name": "Kassadin"})
    conn.execute(query, {"id": "Katarina", "name": "Katarina"})
    conn.execute(query, {"id": "Kayle", "name": "Kayle"})
    conn.execute(query, {"id": "Kayn", "name": "Kayn"})
    conn.execute(query, {"id": "Kennen", "name": "Kennen"})
    conn.execute(query, {"id": "Khazix", "name": "Kha'Zix"})
    conn.execute(query, {"id": "Kindred", "name": "Kindred"})
    conn.execute(query, {"id": "Kled", "name": "Kled"})
    conn.execute(query, {"id": "KogMaw", "name": "Kog'Maw"})
    conn.execute(query, {"id": "KSante", "name": "K'Sante"})
    conn.execute(query, {"id": "Leblanc", "name": "LeBlanc"})
    conn.execute(query, {"id": "LeeSin", "name": "Lee Sin"})
    conn.execute(query, {"id": "Leona", "name": "Leona"})
    conn.execute(query, {"id": "Lillia", "name": "Lillia"})
    conn.execute(query, {"id": "Lissandra", "name": "Lissandra"})
    conn.execute(query, {"id": "Lucian", "name": "Lucian"})
    conn.execute(query, {"id": "Lulu", "name": "Lulu"})
    conn.execute(query, {"id": "Lux", "name": "Lux"})
    conn.execute(query, {"id": "Malphite", "name": "Malphite"})
    conn.execute(query, {"id": "Malzahar", "name": "Malzahar"})
    conn.execute(query, {"id": "Maokai", "name": "Maokai"})
    conn.execute(query, {"id": "MasterYi", "name": "Master Yi"})
    conn.execute(query, {"id": "MissFortune", "name": "Miss Fortune"})
    conn.execute(query, {"id": "MonkeyKing", "name": "Wukong"})
    conn.execute(query, {"id": "Mordekaiser", "name": "Mordekaiser"})
    conn.execute(query, {"id": "Morgana", "name": "Morgana"})
    conn.execute(query, {"id": "Nami", "name": "Nami"})
    conn.execute(query, {"id": "Nasus", "name": "Nasus"})
    conn.execute(query, {"id": "Nautilus", "name": "Nautilus"})
    conn.execute(query, {"id": "Neeko", "name": "Neeko"})
    conn.execute(query, {"id": "Nidalee", "name": "Nidalee"})
    conn.execute(query, {"id": "Nilah", "name": "Nilah"})
    conn.execute(query, {"id": "Nocturne", "name": "Nocturne"})
    conn.execute(query, {"id": "Nunu", "name": "Nunu & Willump"})
    conn.execute(query, {"id": "Olaf", "name": "Olaf"})
    conn.execute(query, {"id": "Orianna", "name": "Orianna"})
    conn.execute(query, {"id": "Ornn", "name": "Ornn"})
    conn.execute(query, {"id": "Pantheon", "name": "Pantheon"})
    conn.execute(query, {"id": "Poppy", "name": "Poppy"})
    conn.execute(query, {"id": "Pyke", "name": "Pyke"})
    conn.execute(query, {"id": "Qiyana", "name": "Qiyana"})
    conn.execute(query, {"id": "Quinn", "name": "Quinn"})
    conn.execute(query, {"id": "Rakan", "name": "Rakan"})
    conn.execute(query, {"id": "Rammus", "name": "Rammus"})
    conn.execute(query, {"id": "RekSai", "name": "Rek'Sai"})
    conn.execute(query, {"id": "Rell", "name": "Rell"})
    conn.execute(query, {"id": "Renata", "name": "Renata Glasc"})
    conn.execute(query, {"id": "Renekton", "name": "Renekton"})
    conn.execute(query, {"id": "Rengar", "name": "Rengar"})
    conn.execute(query, {"id": "Riven", "name": "Riven"})
    conn.execute(query, {"id": "Rumble", "name": "Rumble"})
    conn.execute(query, {"id": "Ryze", "name": "Ryze"})
    conn.execute(query, {"id": "Samira", "name": "Samira"})
    conn.execute(query, {"id": "Sejuani", "name": "Sejuani"})
    conn.execute(query, {"id": "Senna", "name": "Senna"})
    conn.execute(query, {"id": "Seraphine", "name": "Seraphine"})
    conn.execute(query, {"id": "Sett", "name": "Sett"})
    conn.execute(query, {"id": "Shaco", "name": "Shaco"})
    conn.execute(query, {"id": "Shen", "name": "Shen"})
    conn.execute(query, {"id": "Shyvana", "name": "Shyvana"})
    conn.execute(query, {"id": "Singed", "name": "Singed"})
    conn.execute(query, {"id": "Sion", "name": "Sion"})
    conn.execute(query, {"id": "Sivir", "name": "Sivir"})
    conn.execute(query, {"id": "Skarner", "name": "Skarner"})
    conn.execute(query, {"id": "Sona", "name": "Sona"})
    conn.execute(query, {"id": "Soraka", "name": "Soraka"})
    conn.execute(query, {"id": "Swain", "name": "Swain"})
    conn.execute(query, {"id": "Sylas", "name": "Sylas"})
    conn.execute(query, {"id": "Syndra", "name": "Syndra"})
    conn.execute(query, {"id": "TahmKench", "name": "Tahm Kench"})
    conn.execute(query, {"id": "Taliyah", "name": "Taliyah"})
    conn.execute(query, {"id": "Talon", "name": "Talon"})
    conn.execute(query, {"id": "Taric", "name": "Taric"})
    conn.execute(query, {"id": "Teemo", "name": "Teemo"})
    conn.execute(query, {"id": "Thresh", "name": "Thresh"})
    conn.execute(query, {"id": "Tristana", "name": "Tristana"})
    conn.execute(query, {"id": "Trundle", "name": "Trundle"})
    conn.execute(query, {"id": "Tryndamere", "name": "Tryndamere"})
    conn.execute(query, {"id": "TwistedFate", "name": "Twisted Fate"})
    conn.execute(query, {"id": "Twitch", "name": "Twitch"})
    conn.execute(query, {"id": "Udyr", "name": "Udyr"})
    conn.execute(query, {"id": "Urgot", "name": "Urgot"})
    conn.execute(query, {"id": "Varus", "name": "Varus"})
    conn.execute(query, {"id": "Vayne", "name": "Vayne"})
    conn.execute(query, {"id": "Veigar", "name": "Veigar"})
    conn.execute(query, {"id": "Velkoz", "name": "Vel'Koz"})
    conn.execute(query, {"id": "Vex", "name": "Vex"})
    conn.execute(query, {"id": "Vi", "name": "Vi"})
    conn.execute(query, {"id": "Viego", "name": "Viego"})
    conn.execute(query, {"id": "Viktor", "name": "Viktor"})
    conn.execute(query, {"id": "Vladimir", "name": "Vladimir"})
    conn.execute(query, {"id": "Volibear", "name": "Volibear"})
    conn.execute(query, {"id": "Warwick", "name": "Warwick"})
    conn.execute(query, {"id": "Xayah", "name": "Xayah"})
    conn.execute(query, {"id": "Xerath", "name": "Xerath"})
    conn.execute(query, {"id": "XinZhao", "name": "Xin Zhao"})
    conn.execute(query, {"id": "Yasuo", "name": "Yasuo"})
    conn.execute(query, {"id": "Yone", "name": "Yone"})
    conn.execute(query, {"id": "Yorick", "name": "Yorick"})
    conn.execute(query, {"id": "Yuumi", "name": "Yuumi"})
    conn.execute(query, {"id": "Zac", "name": "Zac"})
    conn.execute(query, {"id": "Zed", "name": "Zed"})
    conn.execute(query, {"id": "Zeri", "name": "Zeri"})
    conn.execute(query, {"id": "Ziggs", "name": "Ziggs"})
    conn.execute(query, {"id": "Zilean", "name": "Zilean"})
    conn.execute(query, {"id": "Zoe", "name": "Zoe"})
    conn.execute(query, {"id": "Zyra", "name": "Zyra"})




def downgrade() -> None:
    """Downgrade schema."""

    conn = op.get_bind()
    query = text("DELETE FROM champion WHERE id = :id")

    conn.execute(query, {"id": "Aatrox"})
    conn.execute(query, {"id": "Ahri"})
    conn.execute(query, {"id": "Akali"})
    conn.execute(query, {"id": "Akshan"})
    conn.execute(query, {"id": "Alistar"})
    conn.execute(query, {"id": "Amumu"})
    conn.execute(query, {"id": "Anivia"})
    conn.execute(query, {"id": "Annie"})
    conn.execute(query, {"id": "Aphelios"})
    conn.execute(query, {"id": "Ashe"})
    conn.execute(query, {"id": "AurelionSol"})
    conn.execute(query, {"id": "Azir"})
    conn.execute(query, {"id": "Bard"})
    conn.execute(query, {"id": "Belveth"})
    conn.execute(query, {"id": "Blitzcrank"})
    conn.execute(query, {"id": "Brand"})
    conn.execute(query, {"id": "Braum"})
    conn.execute(query, {"id": "Caitlyn"})
    conn.execute(query, {"id": "Camille"})
    conn.execute(query, {"id": "Cassiopeia"})
    conn.execute(query, {"id": "Chogath"})
    conn.execute(query, {"id": "Corki"})
    conn.execute(query, {"id": "Darius"})
    conn.execute(query, {"id": "Diana"})
    conn.execute(query, {"id": "Draven"})
    conn.execute(query, {"id": "DrMundo"})
    conn.execute(query, {"id": "Ekko"})
    conn.execute(query, {"id": "Elise"})
    conn.execute(query, {"id": "Evelynn"})
    conn.execute(query, {"id": "Ezreal"})
    conn.execute(query, {"id": "Fiddlesticks"})
    conn.execute(query, {"id": "Fiora"})
    conn.execute(query, {"id": "Fizz"})
    conn.execute(query, {"id": "Galio"})
    conn.execute(query, {"id": "Gangplank"})
    conn.execute(query, {"id": "Garen"})
    conn.execute(query, {"id": "Gnar"})
    conn.execute(query, {"id": "Gragas"})
    conn.execute(query, {"id": "Graves"})
    conn.execute(query, {"id": "Gwen"})
    conn.execute(query, {"id": "Hecarim"})
    conn.execute(query, {"id": "Heimerdinger"})
    conn.execute(query, {"id": "Illaoi"})
    conn.execute(query, {"id": "Irelia"})
    conn.execute(query, {"id": "Ivern"})
    conn.execute(query, {"id": "Janna"})
    conn.execute(query, {"id": "JarvanIV"})
    conn.execute(query, {"id": "Jax"})
    conn.execute(query, {"id": "Jayce"})
    conn.execute(query, {"id": "Jhin"})
    conn.execute(query, {"id": "Jinx"})
    conn.execute(query, {"id": "Kaisa"})
    conn.execute(query, {"id": "Kalista"})
    conn.execute(query, {"id": "Karma"})
    conn.execute(query, {"id": "Karthus"})
    conn.execute(query, {"id": "Kassadin"})
    conn.execute(query, {"id": "Katarina"})
    conn.execute(query, {"id": "Kayle"})
    conn.execute(query, {"id": "Kayn"})
    conn.execute(query, {"id": "Kennen"})
    conn.execute(query, {"id": "Khazix"})
    conn.execute(query, {"id": "Kindred"})
    conn.execute(query, {"id": "Kled"})
    conn.execute(query, {"id": "KogMaw"})
    conn.execute(query, {"id": "KSante"})
    conn.execute(query, {"id": "Leblanc"})
    conn.execute(query, {"id": "LeeSin"})
    conn.execute(query, {"id": "Leona"})
    conn.execute(query, {"id": "Lillia"})
    conn.execute(query, {"id": "Lissandra"})
    conn.execute(query, {"id": "Lucian"})
    conn.execute(query, {"id": "Lulu"})
    conn.execute(query, {"id": "Lux"})
    conn.execute(query, {"id": "Malphite"})
    conn.execute(query, {"id": "Malzahar"})
    conn.execute(query, {"id": "Maokai"})
    conn.execute(query, {"id": "MasterYi"})
    conn.execute(query, {"id": "MissFortune"})
    conn.execute(query, {"id": "MonkeyKing"})
    conn.execute(query, {"id": "Mordekaiser"})
    conn.execute(query, {"id": "Morgana"})
    conn.execute(query, {"id": "Nami"})
    conn.execute(query, {"id": "Nasus"})
    conn.execute(query, {"id": "Nautilus"})
    conn.execute(query, {"id": "Neeko"})
    conn.execute(query, {"id": "Nidalee"})
    conn.execute(query, {"id": "Nilah"})
    conn.execute(query, {"id": "Nocturne"})
    conn.execute(query, {"id": "Nunu"})
    conn.execute(query, {"id": "Olaf"})
    conn.execute(query, {"id": "Orianna"})
    conn.execute(query, {"id": "Ornn"})
    conn.execute(query, {"id": "Pantheon"})
    conn.execute(query, {"id": "Poppy"})
    conn.execute(query, {"id": "Pyke"})
    conn.execute(query, {"id": "Qiyana"})
    conn.execute(query, {"id": "Quinn"})
    conn.execute(query, {"id": "Rakan"})
    conn.execute(query, {"id": "Rammus"})
    conn.execute(query, {"id": "RekSai"})
    conn.execute(query, {"id": "Rell"})
    conn.execute(query, {"id": "Renata"})
    conn.execute(query, {"id": "Renekton"})
    conn.execute(query, {"id": "Rengar"})
    conn.execute(query, {"id": "Riven"})
    conn.execute(query, {"id": "Rumble"})
    conn.execute(query, {"id": "Ryze"})
    conn.execute(query, {"id": "Samira"})
    conn.execute(query, {"id": "Sejuani"})
    conn.execute(query, {"id": "Senna"})
    conn.execute(query, {"id": "Seraphine"})
    conn.execute(query, {"id": "Sett"})
    conn.execute(query, {"id": "Shaco"})
    conn.execute(query, {"id": "Shen"})
    conn.execute(query, {"id": "Shyvana"})
    conn.execute(query, {"id": "Singed"})
    conn.execute(query, {"id": "Sion"})
    conn.execute(query, {"id": "Sivir"})
    conn.execute(query, {"id": "Skarner"})
    conn.execute(query, {"id": "Sona"})
    conn.execute(query, {"id": "Soraka"})
    conn.execute(query, {"id": "Swain"})
    conn.execute(query, {"id": "Sylas"})
    conn.execute(query, {"id": "Syndra"})
    conn.execute(query, {"id": "TahmKench"})
    conn.execute(query, {"id": "Taliyah"})
    conn.execute(query, {"id": "Talon"})
    conn.execute(query, {"id": "Taric"})
    conn.execute(query, {"id": "Teemo"})
    conn.execute(query, {"id": "Thresh"})
    conn.execute(query, {"id": "Tristana"})
    conn.execute(query, {"id": "Trundle"})
    conn.execute(query, {"id": "Tryndamere"})
    conn.execute(query, {"id": "TwistedFate"})
    conn.execute(query, {"id": "Twitch"})
    conn.execute(query, {"id": "Udyr"})
    conn.execute(query, {"id": "Urgot"})
    conn.execute(query, {"id": "Varus"})
    conn.execute(query, {"id": "Vayne"})
    conn.execute(query, {"id": "Veigar"})
    conn.execute(query, {"id": "Velkoz"})
    conn.execute(query, {"id": "Vex"})
    conn.execute(query, {"id": "Vi"})
    conn.execute(query, {"id": "Viego"})
    conn.execute(query, {"id": "Viktor"})
    conn.execute(query, {"id": "Vladimir"})
    conn.execute(query, {"id": "Volibear"})
    conn.execute(query, {"id": "Warwick"})
    conn.execute(query, {"id": "Xayah"})
    conn.execute(query, {"id": "Xerath"})
    conn.execute(query, {"id": "XinZhao"})
    conn.execute(query, {"id": "Yasuo"})
    conn.execute(query, {"id": "Yone"})
    conn.execute(query, {"id": "Yorick"})
    conn.execute(query, {"id": "Yuumi"})
    conn.execute(query, {"id": "Zac"})
    conn.execute(query, {"id": "Zed"})
    conn.execute(query, {"id": "Zeri"})
    conn.execute(query, {"id": "Ziggs"})
    conn.execute(query, {"id": "Zilean"})
    conn.execute(query, {"id": "Zoe"})
    conn.execute(query, {"id": "Zyra"})
