"""added relationship

Revision ID: b87ca2bb5a75
Revises: 89d6f7279c4d
Create Date: 2026-03-26 16:37:37.750269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b87ca2bb5a75'
down_revision: Union[str, Sequence[str], None] = '89d6f7279c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Champion_Stats', sa.Column('champion_id', sa.String(), nullable=False))
    op.drop_index(op.f('ix_Champion_Stats_champion_name'), table_name='Champion_Stats')
    op.create_index(op.f('ix_Champion_Stats_champion_id'), 'Champion_Stats', ['champion_id'], unique=False)
    op.create_foreign_key(None, 'Champion_Stats', 'Champion', ['champion_id'], ['id'])
    op.drop_column('Champion_Stats', 'champion_name')
    op.create_foreign_key(None, 'Match_Participant', 'Champion', ['champion'], ['id'])
    op.create_foreign_key(None, 'Match_Participant', 'Match', ['match_id'], ['id'])
    op.create_foreign_key(None, 'Match_Participant', 'Summoner', ['summoner_id'], ['id'])
    op.add_column('Summoner_Champion', sa.Column('champion_id', sa.String(), nullable=False))
    op.drop_index(op.f('ix_Summoner_Champion_champion_name'), table_name='Summoner_Champion')
    op.create_index(op.f('ix_Summoner_Champion_champion_id'), 'Summoner_Champion', ['champion_id'], unique=False)
    op.create_foreign_key(None, 'Summoner_Champion', 'Champion', ['champion_id'], ['id'])
    op.create_foreign_key(None, 'Summoner_Champion', 'Summoner', ['summoner_id'], ['id'])
    op.drop_column('Summoner_Champion', 'champion_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Summoner_Champion', sa.Column('champion_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Summoner_Champion', type_='foreignkey')
    op.drop_constraint(None, 'Summoner_Champion', type_='foreignkey')
    op.drop_index(op.f('ix_Summoner_Champion_champion_id'), table_name='Summoner_Champion')
    op.create_index(op.f('ix_Summoner_Champion_champion_name'), 'Summoner_Champion', ['champion_name'], unique=False)
    op.drop_column('Summoner_Champion', 'champion_id')
    op.drop_constraint(None, 'Match_Participant', type_='foreignkey')
    op.drop_constraint(None, 'Match_Participant', type_='foreignkey')
    op.drop_constraint(None, 'Match_Participant', type_='foreignkey')
    op.add_column('Champion_Stats', sa.Column('champion_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Champion_Stats', type_='foreignkey')
    op.drop_index(op.f('ix_Champion_Stats_champion_id'), table_name='Champion_Stats')
    op.create_index(op.f('ix_Champion_Stats_champion_name'), 'Champion_Stats', ['champion_name'], unique=False)
    op.drop_column('Champion_Stats', 'champion_id')
    # ### end Alembic commands ###
