"""summoner_kda

Revision ID: e2cd94cc629b
Revises: 3f0e1eb169c4
Create Date: 2026-04-08 11:16:55.945784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2cd94cc629b'
down_revision: Union[str, Sequence[str], None] = '3f0e1eb169c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summoner', sa.Column('kill', sa.Integer(), nullable=True))
    op.add_column('summoner', sa.Column('death', sa.Integer(), nullable=True))
    op.add_column('summoner', sa.Column('assist', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    op.execute("""
        CREATE OR REPLACE FUNCTION increment_summoner_games()
    RETURNS TRIGGER AS $$
    BEGIN
        
        UPDATE summoner
        SET 
        games_played = games_played + 1,
        games_won = games_won + 
            CASE WHEN NEW.won THEN 1 ELSE 0 END,
        kill = summoner.kill + new.kill,
        death = summoner.death + new.death,
        assist = summoner.assist + new.assist
        WHERE id = new.summoner_id;

        RETURN new;
    END;
    $$  LANGUAGE plpgsql;
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summoner', 'assist')
    op.drop_column('summoner', 'death')
    op.drop_column('summoner', 'kill')
    # ### end Alembic commands ###

    op.execute("""
    CREATE OR REPLACE FUNCTION increment_summoner_games()
    RETURNS TRIGGER AS $$
    BEGIN
        
        UPDATE summoner
        SET 
        games_played = COALESCE(games_played, 0) + 1,
        games_won = COALESCE(games_won, 0) + 
            CASE WHEN NEW.won THEN 1 ELSE 0 END
        WHERE id = NEW.summoner_id;

        RETURN NEW;
    END;
    $$  LANGUAGE plpgsql;
    """)
