"""adding new champions

Revision ID: ff8928baa8a1
Revises: 50ee3ad46c2e
Create Date: 2026-04-28 10:17:32.895922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = 'ff8928baa8a1'
down_revision: Union[str, Sequence[str], None] = '50ee3ad46c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    conn = op.get_bind()
    query = text("""
                 INSERT INTO champion (id, champion_name, key)
                 VALUES (:id, :name, :key) ON CONFLICT (id) DO
                 UPDATE
                     SET champion_name = EXCLUDED.champion_name, key = EXCLUDED.key
                 """)

    conn.execute(query, {"id": "Naafiri", "name": "Naafiri", "key": "950"})
    conn.execute(query, {"id": "Ambessa", "name": "Ambessa", "key": "799"})
    conn.execute(query, {"id": "Aurora", "name": "Aurora", "key": "893"})
    conn.execute(query, {"id": "Briar", "name": "Briar", "key": "233"})
    conn.execute(query, {"id": "Mel", "name": "Mel", "key": "800"})
    conn.execute(query, {"id": "Hwei", "name": "Hwei", "key": "910"})
    conn.execute(query, {"id": "Milio", "name": "Milio", "key": "902"})
    conn.execute(query, {"id": "Smolder", "name": "Smolder", "key": "901"})
    conn.execute(query, {"id": "Yunara", "name": "Yunara", "key": "804"})
    conn.execute(query, {"id": "Zaahen", "name": "Zaahen", "key": "904"})



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

    conn = op.get_bind()
    query = text("DELETE FROM champion WHERE id = :id")
    conn.execute(query, {"id": "Naafiri"})
    conn.execute(query, {"id": "Ambessa"})
    conn.execute(query, {"id": "Aurora"})
    conn.execute(query, {"id": "Briar"})
    conn.execute(query, {"id": "Mel"})
    conn.execute(query, {"id": "Hwei"})
    conn.execute(query, {"id": "Milio"})
    conn.execute(query, {"id": "Smolder"})
    conn.execute(query, {"id": "Yunara"})
    conn.execute(query, {"id": "Zaahen"})
