flowchart TD
    A[Client] --> B(Prezentační vrstva Views/Templates)
    B --> C[Řídicí vrstva Controllers/Routers]
    C --> D[Aplikační vrstva Services/Business Logic]
    D --> E[Datová vrstva Repositories / Database]
   E --> F[Database]