erDiagram
   Match {
        string id PK
        int created
        int ended
        string gametype
        string patch
    } 
    Match_Participant{
        string summoner_id PK,FK
        string match_id PK, FK
        int kill
        int death
        int assist
        int gold
        int team
        int won
        int champion FK
    }
    Champion{
        string id 
        string name PK
    }
    champion_stats{
        string champion PK, FK
        string patch PK
        string gametype PK
        int game_played 
        int game_won 
        int games_picked
        int games_ban
        int kill
        int death
        int assist
    }
    Summoner{
        string name  "INDEX"
        string id PK
        int game_played
        int game_won
    }

    Summoner ||--o{ Match_Participant : ""
    Match ||--o{ Match_Participant : ""
    Champion ||--o{ Match_Participant : ""
    Champion ||--o{ champion_stats : ""



